### ISSUE TITLE
issue-1-user-can-view-list-of-exercises

### ISSUE THREAD

**Issue by ErikModica** [ErikModica/Workout-Vault#1]
## 📐 Plan

Create an archive of exercises that the user can access by choosing a muscle group.

## 🖼️ Wireframes
Mobile
![image](https://user-images.githubusercontent.com/76715055/113757738-d0c28780-96c7-11eb-8cdc-c88df6acf2fc.png)

Desktop
![image](https://user-images.githubusercontent.com/76715055/113757506-88a36500-96c7-11eb-931f-2750515ef116.png)

## ✅ Task List

- [x] Add the basic HTML skeleton for the page and style it with CSS.
- [x] Figure out the structure and styling for the Home page.
- [x] Figure out the structure and styling for the Exercises page.
- [x] Add appropriate code to show Exercises page when the panel is clicked as well as the home page when the home icon is clicked.
- [x] Add all muscle groups to the accordion mobile exercise page structure.
- [x] Add an OnClick function that retrieves data from the REST API for the appropriate muscle group.
- [x] Display retrieved information on second layer of accordion. 
- [x] Add OnClick function to second layer items that shows the desired exercise when clicked.
- [x] Add media queries so that layout changes when on a wider screen
