### ISSUE TITLE
issue-3-user-can-view-saved-exercises

### ISSUE THREAD

**Issue by ErikModica** [ErikModica/Workout-Vault#14]
## 📐 Plan

User has the ability to see the exercises they saved

## 🖼️ Wireframes
Mobile
![image](https://user-images.githubusercontent.com/76715055/114946115-6dd79b80-9dff-11eb-8a49-06c615e8ed20.png)

Desktop
![image](https://user-images.githubusercontent.com/76715055/114946013-42ed4780-9dff-11eb-9399-6c8027b38064.png)

## ✅ Task List

- [x] create function in index.js that gets saved muscle groups from the database
- [x] display fetched muscle groups
- [x] create function in index.js that gets saved exercises based on the muscleName
- [x] display fetched exercises when the user clicks on the muscle group
- [x] fetch for the exercise info when user clicks on exercises name
- [x] display fetched data
- [x] implement this into the desktop version
- [x] test for bugs
