### ISSUE TITLE
issue-6-user-can-view-created-workouts

### ISSUE THREAD

**Issue by ErikModica** [ErikModica/Workout-Vault#18]
## 📐 Plan

View previously created workouts 

## 🖼️ Wireframes
Mobile
![image](https://user-images.githubusercontent.com/76715055/116129746-501bf900-a67f-11eb-91e8-79c474bb8cdf.png)

Desktop
![image](https://user-images.githubusercontent.com/76715055/116129834-675ae680-a67f-11eb-8d1f-b4e970c03a9c.png)
![image](https://user-images.githubusercontent.com/76715055/116129868-6f1a8b00-a67f-11eb-9589-d144e2c0b152.png)

## ✅ Task List

- [x] implement the proper files and add the HTML skeleton and CSS design to them
- [x] add hash routing to new pages
- [x] set up a fetch request that gets the created workout information from the database and print it to console
- [x] load the title of the workout to both accordion and app drawer styles and pass the other information as props to the respected tiles
- [x] add hash routing to the tiles that opens the user workout page that loads the appropriate information to the console.
- [x] create a loose styling that displays the exercise information in both desktop and mobile
- [x] add the details button that when clicked displays a modal of the exercise information(like in search exercises)
- [x] fix any bugs or add tasks
