### ISSUE TITLE
issue-2-user-can-save-an-exercise

### ISSUE THREAD

**Issue by ErikModica** [ErikModica/Workout-Vault#2]
## 📐 Plan

Create a personal archive of saved exercises so that the user can view them at any time.

## 🖼️ Wireframes
Mobile
![image](https://user-images.githubusercontent.com/76715055/114944125-e3416d00-9dfb-11eb-9617-b7d17f574726.png)

Desktop
![image](https://user-images.githubusercontent.com/76715055/114944210-05d38600-9dfc-11eb-9be5-124c44ac1997.png)

## ✅ Task List

- [x] add the proper directories and files for this issue
- [x] add a tile for the saved exercises page
- [x] add the html and CSS structure for the saved exercises page
- [x] implement the hash routing for the saved exercises page
- [x] create a database that has a table for users and saved exercise ID's
- [x] in index.js add a post request that adds exercise IDs to new table
- [x] add unsaved icons to exercise tabs
- [x] add a function in the appropriate components that sends the exercise id to the post request in index.js
- [x] add a function that changes the state of the icons to saved icons when clicked on.
