### ISSUE TITLE
issue-5-user-can-create-a-workout

### ISSUE THREAD

**Issue by ErikModica** [ErikModica/Workout-Vault#3]
## 📐 Plan

Create a personal workout that can have multiple exercises added to it.

## 🖼️ Wireframes
Mobile
![image](https://user-images.githubusercontent.com/76715055/115934231-69d1fc00-a445-11eb-8961-e9ccf8c44025.png)

Desktop
![image](https://user-images.githubusercontent.com/76715055/115934649-69863080-a446-11eb-82fc-5dba545f909a.png)

## ✅ Task List

- [x] add the proper directories and files for this issue
- [x] style these files with the proper HTML and CSS
- [x] create the hash routing between new pages 
- [x] add the basic form layout for the create workout page
- [x] load proper exercises to the appropriate muscle group selected.
