### ISSUE TITLE
issue-7-user-can-set-variations-to-workout

### ISSUE THREAD

**Issue by ErikModica** [ErikModica/Workout-Vault#4]
## 📐 Plan

Customize the workout to be able to add sets, reps, weight, etc..

## 🖼️ Wireframes
Mobile
![image](https://user-images.githubusercontent.com/76715055/113758573-e5534f80-96c8-11eb-836b-9c9f1b33def0.png)

Desktop
![image](https://user-images.githubusercontent.com/76715055/113758513-d40a4300-96c8-11eb-9adb-674d7c0dd278.png)

## ✅ Task List

- [x] add a sets button and fix formatting a bit
- [x] add an onClick function to the sets button that displays blank tabs for the amount of sets chosen
- [x] add two fields to the sets tab, reps and weight(let reps cap at 100 and weight cap at 1000)
- [x] add an extra settings drop down to the sets tabs and an onClick function that opens it.
- [x] add two fields to the extra settings drop down, Alternation and Duration.
- [x] modify the submit function and make sure it collects all the new information added.
- [ ] modify the fetch requests in index.js so that they comply with the new data.
- [ ] make sure that the information is correct in the User Workouts page,.
- [ ] reformat the User Workout page to make it look cleaner.
- [ ] display the information received from the fetch calls to the newly formatted page
- [ ] check for any bugs.
